// Code generated by "stringer --type ErrorCode"; DO NOT EDIT.

package commands

import "strconv"

const _ErrorCode_name = "NoReplicationEnabled"

var _ErrorCode_index = [...]uint8{0, 20}

func (i ErrorCode) String() string {
	i -= 76
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+76), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
