// Code generated by "stringer --type ErrorCode"; DO NOT EDIT.

package commands

import "strconv"

const (
	_ErrorCode_name_0 = "BadValue"
	_ErrorCode_name_1 = "NoReplicationEnabled"
)

func (i ErrorCode) String() string {
	switch {
	case i == 2:
		return _ErrorCode_name_0
	case i == 76:
		return _ErrorCode_name_1
	default:
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
