// Code generated by "stringer --type OpCode"; DO NOT EDIT.

package protocol

import "strconv"

const (
	_OpCode_name_0 = "OpReply"
	_OpCode_name_1 = "OpUpdateOpInsertReservedOpQueryOpGetMoreOpDeleteOpKillCursors"
	_OpCode_name_2 = "OpCommandOpCommandreply"
	_OpCode_name_3 = "OpMsg"
)

var (
	_OpCode_index_1 = [...]uint8{0, 8, 16, 24, 31, 40, 48, 61}
	_OpCode_index_2 = [...]uint8{0, 9, 23}
)

func (i OpCode) String() string {
	switch {
	case i == 1:
		return _OpCode_name_0
	case 2001 <= i && i <= 2007:
		i -= 2001
		return _OpCode_name_1[_OpCode_index_1[i]:_OpCode_index_1[i+1]]
	case 2010 <= i && i <= 2011:
		i -= 2010
		return _OpCode_name_2[_OpCode_index_2[i]:_OpCode_index_2[i+1]]
	case i == 2013:
		return _OpCode_name_3
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
